### ISSUE TITLE
Support for Interstial VIDEO?

### ISSUE THREAD

**Issue by mzhukovs** [marcojak/TestMTAdmob#3]
Greetings, Thanks for this great package.

when I use the ShowInterstitial method for a regular Interstitial, it works fine, however, when I use it for an Interstitial Video (e.g. here is the ad unit ID for an android TEST interstital video) ca-app-pub-3940256099942544/8691691433 , it fails - does this mean that the interstital videos are just not supported yet (and if not, will they be soon?) or that I am missing some sort of config?

**Comment by marcojak** [comment]
Hi,

Are you sure you are not referring to the Rewarded Video? If so, they are supported.
If there are Interstitial Videos (I'm not aware of eight now), I'll add them to the next version of MTAdmob.

Cheers
