### ISSUE TITLE
Latest Xamarin 4.6

### ISSUE THREAD

**Issue by scorrin** [marcojak/TestMTAdmob#5]
I have updated the packages as follows and the solution no longer builds:

MarcTron.Admob 1.5.5
Xamarin.Forms 4.6.0.772
Xamarin.Google.iOS.MobileAds 7.57.0
Xamarin.Google.iOS.SignIn 5.0.2.1

Has anyone tried updating to the latest versions?

EDIT:
I got this to work after reading lots of comments, if you remove Google.iOS.SignIn then it all works again.

**Comment by marcojak** [comment]
Remove the sign-in package, clean the solution, delete bin and obj folders
and it should work.
Later I'll update the project.

Thanks for letting me know
